---

auth_enabled: false

global:
  image:
    registry: null
  priorityClassName: null
  clusterDomain: "cluster.local"
  dnsService: "kube-dns"
  dnsNamespace: "kube-system"

backend:
  replicas: 2

singleBinary:
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage:
write:
  replicas: 2
read:
  replicas: 2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage:

loki:
  #storage:
  #  bucketNames:
  #    chunks: chunks
  #    ruler: ruler
  #    admin: admin
  #  type: s3
  #  s3:
  #    s3: null
  #    endpoint: null
  #    region: null
  #    secretAccessKey: null
  #    accessKeyId: null
  #    s3ForcePathStyle: false
  #    insecure: false
  #    http_config: {}
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

monitoring:
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: false
  lokiCanary:
    enabled: true

test:
  enabled: true
